//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_logs
    {
        public int ID { get; set; }
        public string tablename { get; set; }
        public Nullable<int> tableid { get; set; }
        public string columnname { get; set; }
        public string value { get; set; }
        public string action { get; set; }
        public Nullable<int> user_id { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> logdate { get; set; }
        public byte deleted { get; set; }
    }
}
