//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_relation
    {
        public int ID { get; set; }
        public Nullable<short> Location { get; set; }
        public string Tablename { get; set; }
        public string Tablerel { get; set; }
        public string Name { get; set; }
        public Nullable<int> Sort { get; set; }
        public byte Deleted { get; set; }
    }
}
