//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_union
    {
        public int ID { get; set; }
        public string Tablename { get; set; }
        public string Columns { get; set; }
    }
}
