//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class citywastestream
    {
        public int ID { get; set; }
        public Nullable<int> City_ID { get; set; }
        public string Year { get; set; }
        public string estimated { get; set; }
        public Nullable<int> Wastecategory_ID { get; set; }
        public string Definitions { get; set; }
        public string Definedby { get; set; }
        public string Totalgenerated { get; set; }
        public string Hazardous { get; set; }
        public string Totalcollected { get; set; }
        public string Recycled { get; set; }
        public string Recovered { get; set; }
        public string Disposal { get; set; }
        public string Treatment { get; set; }
        public string Reuse { get; set; }
        public string Sludge { get; set; }
        public string Datasource { get; set; }
        public Nullable<System.DateTime> Dateentered { get; set; }
        public Nullable<byte> Deleted { get; set; }
        public string Reference { get; set; }
        public string WasteComposition { get; set; }
        public string Totalgenerated_ { get; set; }
        public string Hazardous_ { get; set; }
        public string Totalcollected_ { get; set; }
        public string Recycled_ { get; set; }
        public string Recovered_ { get; set; }
        public string Disposal_ { get; set; }
        public string Treatment_ { get; set; }
        public string Reuse_ { get; set; }
        public string Sludge_ { get; set; }
    }
}
