//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class citypopulation
    {
        public int ID { get; set; }
        public Nullable<int> City_ID { get; set; }
        public string Year { get; set; }
        public string Population { get; set; }
        public string Urbanpopulation { get; set; }
        public string Area { get; set; }
        public string Incomelevel { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> Dateentered { get; set; }
        public Nullable<byte> Deleted { get; set; }
    }
}
