//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class conference
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Detail { get; set; }
        public string Thumbnail { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> Datestart { get; set; }
        public Nullable<System.DateTime> Dateend { get; set; }
        public Nullable<int> Country_ID { get; set; }
        public Nullable<int> Geotheme_ID { get; set; }
        public Nullable<int> Conferencescategory_ID { get; set; }
        public Nullable<int> Conferencescontacts_ID { get; set; }
        public Nullable<int> Viewconferences_ID { get; set; }
        public Nullable<int> Conferencescomment_ID { get; set; }
        public Nullable<int> conferencesmedia_ID { get; set; }
        public Nullable<System.DateTime> Dateentered { get; set; }
        public Nullable<byte> Deleted { get; set; }
        public string Referencelink { get; set; }
    }
}
