//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class countrywastestream
    {
        public int ID { get; set; }
        public string Year { get; set; }
        public string estimated { get; set; }
        public string Country_ID { get; set; }
        public string Wastecategory_ID { get; set; }
        public string Definitions { get; set; }
        public string Definedby { get; set; }
        public Nullable<decimal> Totalgenerated { get; set; }
        public Nullable<decimal> Hazardous { get; set; }
        public Nullable<decimal> Totalcollected { get; set; }
        public Nullable<decimal> Recycled { get; set; }
        public Nullable<decimal> Recovered { get; set; }
        public Nullable<decimal> Disposal { get; set; }
        public Nullable<decimal> Treatment { get; set; }
        public Nullable<decimal> Reuse { get; set; }
        public Nullable<decimal> Sludge { get; set; }
        public string datasource { get; set; }
        public string reference { get; set; }
        public short countryreferences_id { get; set; }
        public Nullable<System.DateTime> Dateentered { get; set; }
        public bool Deleted { get; set; }
        public string WasteComposition { get; set; }
    }
}
