//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class countrypolicy
    {
        public int ID { get; set; }
        public string Legal { get; set; }
        public string Year { get; set; }
        public string Description { get; set; }
        public string Country_ID { get; set; }
        public Nullable<System.DateTime> Dateentered { get; set; }
        public Nullable<byte> Deleted { get; set; }
        public string code_number { get; set; }
        public Nullable<int> Type_ID { get; set; }
        public Nullable<int> Area_ID { get; set; }
        public Nullable<int> WasteCategory_ID { get; set; }
        public string Link { get; set; }
        public string fileupload { get; set; }
    }
}
