//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class document
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Documentcategory_ID { get; set; }
        public Nullable<int> City_ID { get; set; }
        public Nullable<int> Region_ID { get; set; }
        public string Country_ID { get; set; }
        public Nullable<int> Geotheme_ID { get; set; }
        public string Attachment { get; set; }
        public string Description { get; set; }
        public string Datasource { get; set; }
        public string Thumbnail { get; set; }
        public string Keyword { get; set; }
        public string Year { get; set; }
        public string Publisher { get; set; }
        public string Subtitle { get; set; }
        public Nullable<System.DateTime> Dateentered { get; set; }
        public Nullable<byte> Deleted { get; set; }
        public string Location { get; set; }
    }
}
