//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class forum
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> geotheme_id { get; set; }
        public Nullable<System.DateTime> Dateentered { get; set; }
        public Nullable<byte> Deleted { get; set; }
        public string Contactquestion { get; set; }
        public Nullable<System.DateTime> ForumDate { get; set; }
        public Nullable<int> ForumContact_ID { get; set; }
    }
}
