//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCOnline.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KnowWasteEntities : DbContext
    {
        public KnowWasteEntities()
            : base("name=KnowWasteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_logs> C_logs { get; set; }
        public virtual DbSet<C_reference> C_reference { get; set; }
        public virtual DbSet<C_relation> C_relation { get; set; }
        public virtual DbSet<C_union> C_union { get; set; }
        public virtual DbSet<academicreport> academicreports { get; set; }
        public virtual DbSet<admincity> admincities { get; set; }
        public virtual DbSet<admincountry> admincountries { get; set; }
        public virtual DbSet<application> applications { get; set; }
        public virtual DbSet<backgroundpaper> backgroundpapers { get; set; }
        public virtual DbSet<backgroundpapercategory> backgroundpapercategories { get; set; }
        public virtual DbSet<blog> blogs { get; set; }
        public virtual DbSet<blogscategory> blogscategories { get; set; }
        public virtual DbSet<blogscomment> blogscomments { get; set; }
        public virtual DbSet<blogscontact> blogscontacts { get; set; }
        public virtual DbSet<blogsmedia> blogsmedias { get; set; }
        public virtual DbSet<casestudy> casestudies { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<citypolicy> citypolicies { get; set; }
        public virtual DbSet<citypopulation> citypopulations { get; set; }
        public virtual DbSet<cityreference> cityreferences { get; set; }
        public virtual DbSet<citywastestream> citywastestreams { get; set; }
        public virtual DbSet<conference> conferences { get; set; }
        public virtual DbSet<conferencescategory> conferencescategories { get; set; }
        public virtual DbSet<conferencescomment> conferencescomments { get; set; }
        public virtual DbSet<conferencescontact> conferencescontacts { get; set; }
        public virtual DbSet<conferencesregistration> conferencesregistrations { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<countrypolicy> countrypolicies { get; set; }
        public virtual DbSet<countrypolicy_area> countrypolicy_area { get; set; }
        public virtual DbSet<countrypopulation> countrypopulations { get; set; }
        public virtual DbSet<countryreference> countryreferences { get; set; }
        public virtual DbSet<countrywastestream> countrywastestreams { get; set; }
        public virtual DbSet<cours> courses { get; set; }
        public virtual DbSet<dashboard> dashboards { get; set; }
        public virtual DbSet<dashboardapplication> dashboardapplications { get; set; }
        public virtual DbSet<documentcategory> documentcategories { get; set; }
        public virtual DbSet<document> documents { get; set; }
        public virtual DbSet<documenttype> documenttypes { get; set; }
        public virtual DbSet<eventregistration> eventregistrations { get; set; }
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<eventscategory> eventscategories { get; set; }
        public virtual DbSet<eventscomment> eventscomments { get; set; }
        public virtual DbSet<expertroster> expertrosters { get; set; }
        public virtual DbSet<expertrosterscategory> expertrosterscategories { get; set; }
        public virtual DbSet<faq> faqs { get; set; }
        public virtual DbSet<forumanswer> forumanswers { get; set; }
        public virtual DbSet<forumcontact> forumcontacts { get; set; }
        public virtual DbSet<forum> forums { get; set; }
        public virtual DbSet<geotheme> geothemes { get; set; }
        public virtual DbSet<lawpolicy> lawpolicies { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<newscategory> newscategories { get; set; }
        public virtual DbSet<newscomment> newscomments { get; set; }
        public virtual DbSet<newsmedia> newsmedias { get; set; }
        public virtual DbSet<privilege> privileges { get; set; }
        public virtual DbSet<region> regions { get; set; }
        public virtual DbSet<reportcategory> reportcategories { get; set; }
        public virtual DbSet<sector> sectors { get; set; }
        public virtual DbSet<seminar> seminars { get; set; }
        public virtual DbSet<seminarscategory> seminarscategories { get; set; }
        public virtual DbSet<seminarscomment> seminarscomments { get; set; }
        public virtual DbSet<seminarscontact> seminarscontacts { get; set; }
        public virtual DbSet<seminarsmedia> seminarsmedias { get; set; }
        public virtual DbSet<seminarsregistration> seminarsregistrations { get; set; }
        public virtual DbSet<subregion> subregions { get; set; }
        public virtual DbSet<tallbuildingfeedbackone> tallbuildingfeedbackones { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<userprivilege> userprivileges { get; set; }
        public virtual DbSet<usertype> usertypes { get; set; }
        public virtual DbSet<usertypeapp> usertypeapps { get; set; }
        public virtual DbSet<usertypeappsub> usertypeappsubs { get; set; }
        public virtual DbSet<videopost> videoposts { get; set; }
        public virtual DbSet<videoposts_old> videoposts_old { get; set; }
        public virtual DbSet<view> views { get; set; }
        public virtual DbSet<wastecategory> wastecategories { get; set; }
        public virtual DbSet<wastetype> wastetypes { get; set; }
        public virtual DbSet<countrypolicy_type> countrypolicy_type { get; set; }
        public virtual DbSet<microlearning> microlearnings { get; set; }
    }
}
