//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Detail { get; set; }
        public Nullable<System.DateTime> NewsDate { get; set; }
        public string Thumbnail { get; set; }
        public string Author { get; set; }
        public Nullable<int> Country_ID { get; set; }
        public Nullable<int> Geotheme_ID { get; set; }
        public Nullable<int> Viewsnews_ID { get; set; }
        public Nullable<int> Newscategory_Id { get; set; }
        public Nullable<int> Newscomment_Id { get; set; }
        public Nullable<int> Newsmedia_Id { get; set; }
        public Nullable<System.DateTime> Dateentered { get; set; }
        public Nullable<byte> Deleted { get; set; }
    }
}
