//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tallbuildingfeedbackone
    {
        public int ID { get; set; }
        public string overalluseful { get; set; }
        public string technicalcontent { get; set; }
        public string speakerresult { get; set; }
        public string venueresult { get; set; }
        public string networkingresult { get; set; }
    }
}
