//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class usertypeappsub
    {
        public int ID { get; set; }
        public Nullable<int> usertypeapps_id { get; set; }
        public Nullable<int> application_id { get; set; }
        public Nullable<System.DateTime> dateentered { get; set; }
        public Nullable<byte> deleted { get; set; }
    }
}
